"""
Recon Sentinel — WAF Fingerprint Agent
Identifies web application firewalls by analyzing response headers,
error pages, and behavioral signatures. Results inform downstream
agents' evasion strategies (UA rotation, rate limits, jitter).

Phase: Active (sends trigger probes that may be logged by WAF/IDS)
MITRE: T1592 (Gather Victim Host Information)

Note: This agent sends crafted payloads (SQLi, XSS, path traversal)
to trigger WAF blocking behavior. These are NOT exploitation attempts
but will appear in target's WAF logs.
"""

import hashlib
import logging

import httpx

from app.agents.base import BaseAgent
from app.core.celery_app import celery_app
from app.models.enums import FindingType, FindingSeverity

logger = logging.getLogger(__name__)

# WAF signatures: header patterns, cookie names, and server values
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": {"server": "cloudflare", "cf-ray": True, "cf-cache-status": True},
        "cookies": ["__cfduid", "__cf_bm", "cf_clearance"],
    },
    "AWS WAF / CloudFront": {
        "headers": {"x-amz-cf-id": True, "x-amz-cf-pop": True, "server": "cloudfront"},
        "cookies": ["awsalb", "awsalbcors"],
    },
    "Akamai": {
        "headers": {"x-akamai-transformed": True, "server": "akamaighost"},
        "cookies": ["akamai_generated", "ak_bmsc"],
    },
    "Imperva / Incapsula": {
        "headers": {"x-iinfo": True, "x-cdn": "imperva"},
        "cookies": ["incap_ses_", "visid_incap_", "nlbi_"],
    },
    "Sucuri": {
        "headers": {"x-sucuri-id": True, "server": "sucuri"},
        "cookies": ["sucuri_cloudproxy_uuid"],
    },
    "F5 BIG-IP": {
        "headers": {"server": "big-ip", "x-wa-info": True},
        "cookies": ["bigipserver", "BIGipServer"],
    },
    "Barracuda": {
        "headers": {"server": "barracuda"},
        "cookies": ["barra_counter_session"],
    },
    "Fortinet / FortiWeb": {
        "headers": {"server": "fortiweb"},
        "cookies": ["FORTIWAFSID"],
    },
    "ModSecurity": {
        "headers": {"server": "mod_security"},
        "error_patterns": ["mod_security", "modsecurity", "NOYB"],
    },
    "Wordfence": {
        "error_patterns": ["wordfence", "generated by wordfence"],
        "cookies": ["wfwaf-authcookie"],
    },
    "DDoS-Guard": {
        "headers": {"server": "ddos-guard"},
        "cookies": ["__ddg1_", "__ddg2_"],
    },
    "Reblaze": {
        "headers": {"server": "reblaze"},
        "cookies": ["rbzid"],
    },
}


class WAFAgent(BaseAgent):
    agent_type = "waf"
    agent_name = "WAF Fingerprint Detection"
    mitre_tags = ["T1592"]
    max_retries = 1

    async def execute(self) -> list[dict]:
        target = self.target_value
        findings = []

        # ─── Phase 1: Normal request ──────────────────────────
        await self.report_progress(10, "Sending probe requests...")
        normal_resp = await self._probe(f"https://{target}/", "normal")
        http_resp = await self._probe(f"http://{target}/", "http_fallback")

        # ─── Phase 2: Malicious-looking requests to trigger WAF ───
        await self.report_progress(30, "Sending trigger requests...")
        sqli_resp = await self._probe(f"https://{target}/?id=1' OR '1'='1", "sqli_trigger")
        xss_resp = await self._probe(f"https://{target}/?q=<script>alert(1)</script>", "xss_trigger")
        path_resp = await self._probe(f"https://{target}/../../etc/passwd", "traversal_trigger")
        ua_resp = await self._probe(f"https://{target}/", "scanner_ua", headers={"User-Agent": "sqlmap/1.0"})

        # ─── Phase 3: Analyze all responses ───────────────────
        await self.report_progress(60, "Analyzing WAF signatures...")

        all_responses = [r for r in [normal_resp, http_resp, sqli_resp, xss_resp, path_resp, ua_resp] if r]
        detected_wafs = set()
        evidence = {}

        for resp in all_responses:
            headers = resp.get("headers", {})
            cookies = resp.get("cookies", {})
            body = resp.get("body_snippet", "").lower()

            for waf_name, sigs in WAF_SIGNATURES.items():
                matches = []

                # Check headers
                for hdr_name, hdr_value in sigs.get("headers", {}).items():
                    actual = headers.get(hdr_name, "").lower()
                    if hdr_value is True and actual:
                        matches.append(f"header:{hdr_name}={actual[:50]}")
                    elif isinstance(hdr_value, str) and hdr_value.lower() in actual:
                        matches.append(f"header:{hdr_name}={actual[:50]}")

                # Check cookies
                for cookie_name in sigs.get("cookies", []):
                    for actual_cookie in cookies:
                        if cookie_name.lower() in actual_cookie.lower():
                            matches.append(f"cookie:{actual_cookie}")

                # Check error page patterns
                for pattern in sigs.get("error_patterns", []):
                    if pattern.lower() in body:
                        matches.append(f"body_pattern:{pattern}")

                if matches:
                    detected_wafs.add(waf_name)
                    evidence[waf_name] = evidence.get(waf_name, []) + matches

        # ─── Phase 4: Behavioral analysis ─────────────────────
        await self.report_progress(80, "Behavioral analysis...")

        # Check if WAF blocked the malicious requests
        blocked = False
        block_codes = {403, 406, 429, 503}
        if sqli_resp and sqli_resp.get("status") in block_codes:
            blocked = True
        if xss_resp and xss_resp.get("status") in block_codes:
            blocked = True

        # ─── Phase 5: Generate findings ───────────────────────
        if detected_wafs:
            for waf_name in detected_wafs:
                waf_evidence = evidence.get(waf_name, [])
                severity = FindingSeverity.INFO

                findings.append({
                    "finding_type": FindingType.WAF_DETECTION,
                    "severity": severity,
                    "value": f"WAF detected: {waf_name}",
                    "detail": (
                        f"Identified {waf_name} protecting {target}. "
                        f"Evidence: {', '.join(waf_evidence[:5])}. "
                        f"{'Actively blocking malicious requests.' if blocked else 'Passive detection only.'}"
                    ),
                    "mitre_technique_ids": ["T1592"],
                    "fingerprint": hashlib.sha256(f"waf:{target}:{waf_name}".encode()).hexdigest()[:32],
                    "raw_data": {
                        "waf_name": waf_name,
                        "evidence": waf_evidence[:10],
                        "blocks_attacks": blocked,
                    },
                    "tags": ["waf", waf_name.lower().replace(" ", "_").replace("/", "_")],
                })
        else:
            findings.append({
                "finding_type": FindingType.WAF_DETECTION,
                "severity": FindingSeverity.INFO,
                "value": f"No WAF detected on {target}",
                "detail": "No known WAF signatures found in response headers, cookies, or error pages.",
                "mitre_technique_ids": ["T1592"],
                "fingerprint": hashlib.sha256(f"waf:none:{target}".encode()).hexdigest()[:32],
                "raw_data": {"waf_name": None, "blocks_attacks": blocked},
                "tags": ["waf", "no_waf"],
            })

        await self.report_progress(100, f"WAF detection complete: {len(detected_wafs)} WAF(s) found")
        return findings

    async def _probe(self, url: str, probe_type: str, headers: dict | None = None) -> dict | None:
        """Send a probe request and collect response metadata."""
        from app.agents.evasion import random_ua
        default_headers = {"User-Agent": random_ua()}
        if headers:
            default_headers.update(headers)

        try:
            async with httpx.AsyncClient(timeout=10, follow_redirects=True) as client:
                resp = await client.get(url, headers=default_headers)
                return {
                    "probe_type": probe_type,
                    "status": resp.status_code,
                    "headers": dict(resp.headers),
                    "cookies": list(resp.cookies.keys()),
                    "body_snippet": resp.text[:2000] if resp.text else "",
                }
        except httpx.ConnectError:
            # SSL/connection error — retry without verification
            try:
                async with httpx.AsyncClient(timeout=10, follow_redirects=True, verify=False) as client:
                    resp = await client.get(url, headers=default_headers)
                    return {
                        "probe_type": probe_type,
                        "status": resp.status_code,
                        "headers": dict(resp.headers),
                        "cookies": list(resp.cookies.keys()),
                        "body_snippet": resp.text[:2000] if resp.text else "",
                        "ssl_verify_disabled": True,
                    }
            except Exception:
                return None
        except Exception as e:
            logger.debug(f"WAF probe {probe_type} failed: {e}")
            return None


@celery_app.task(name="app.agents.waf.run_waf_agent")
def run_waf_agent(scan_id: str, target_value: str, project_id: str, config: dict | None = None):
    import asyncio
    return asyncio.run(WAFAgent(scan_id, target_value, project_id, config).run())
